services:
  postgres:
    image: postgres:15
    container_name: pegaspay-db
    environment:
      POSTGRES_USER: pp_user
      POSTGRES_PASSWORD: pp_pass
      POSTGRES_DB: pegaspay_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: pegaspay-kk
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  db_data: