services:
  postgres:
    image: postgres:15
    container_name: pegaspay-db
    environment:
      POSTGRES_USER: pp_user
      POSTGRES_PASSWORD: pp_pass
      POSTGRES_DB: pegaspay_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: pegaspay-kk
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_PORT: 5432
      KC_DB_USERNAME: pp_user
      KC_DB_PASSWORD: pp_pass
      KC_DB_URL_DATABASE: pegaspay_db
      KC_DB_SCHEMA: keycloak_dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db_data: